# Generated by Django 2.1 on 2019-09-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('unesco', '0003_auto_20190926_1731'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='States',
        ),
        migrations.RenameField(
            model_name='site',
            old_name='state',
            new_name='states',
        ),
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
