# Generated by Django 2.1 on 2019-09-26 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0005_auto_20190926_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='area_hectares',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.DeleteModel(
            name='Area_hectares',
        ),
        migrations.DeleteModel(
            name='Latitude',
        ),
        migrations.DeleteModel(
            name='Longitude',
        ),
    ]
